### PR TITLE
New settings window design

### LINKED ISSUE #87: Redesign Preferences Window
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Too much stuff going in the preferences window, chaotic, not nice.

### Describe the solution you'd like

Something that doesn't hurt when I look at it

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### LINKED ISSUE #106: Hide menu bar icon
### Discussed in https://github.com/AlexPerathoner/SlimHUD/discussions/105

<div type='discussions-op-text'>

<sup>Originally posted by **systracer** January 16, 2023</sup>
Please add ability to hide icon in menu bar.</div>

### PR DESCRIPTION
**Pull request by AlexPerathoner**
Fix #87 
Fix #106 

Depends on #70 

- [x] tabs
- [x] tabs views mechanism
- [x] content of tabs views
    - [x] config
    - [x] style
    - [x] design
    - [x] about
- [x] support for dark mode
- [x] connecting all outlets back
    - [x] config
    - [x] style
    - [x] design
    - [x] about
- [x] reset buttons should be red
- [x] changing light / dark mode while app open not working
- [x] use cmd + 1...4 to select tab
- [x] investigate bug: green volume bar on start (sometimes)
- [x] radio buttons for edge selection should have bigger hitbox
- [x] update preview mechanism
    - [x] add play animation button
- [x] add UI tests
- [x] update screenshots
- [x] update readme
- [x] icons disappear when changing horizontal <-> vertical position
- [x] keyboard icon too big
- [x] beta download not working

### CODE REVIEW

**Comment by AlexPerathoner** [comment]
Current progress (no functionality, just switching style between buttons)
Screenshot 2023-01-23 alle 21 51 27

**Comment by AlexPerathoner** [comment]
No functionality, only elements in config tab

Screenshot 2023-01-24 alle 00 27 47

**Comment by AlexPerathoner** [comment]
I couldn't find a way to export it, and since many elements are custom anyway, I decided to manually do everything.

Health is more important than any design, take care! :3

**Comment by kaydenanderson** [comment]
hi again! i decided to try my hand at Swift design and came up with this as a first attempt. hopefully i can get it as close to native as possible :)
Screenshot 2023-01-23 at 11 55 21 PM

**Comment by AlexPerathoner** [comment]
Nice, the dark design is exactly what I wanted to ask you 👍

**Comment by kaydenanderson** [comment]
hi! good afternoon!
so i finished the initial layouts but can't figure out how to add a checkbox or slider or anything. swift is hard :/
if i send over the file do you think you'd be able to add everything else? it's just the preferences window (the default ContentView is still a "Hello, world!")

**Comment by AlexPerathoner** [comment]
Hi! It's mostly done already. But if you want, I can teach you a bit. Do you have discord?

**Pull request merged**
